version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"

volumes:
  mongo-data:
